/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST3; // mengelompokkan kelas 

import java.awt.image.BufferedImage; 
import java.io.File;
import java.io.IOException; // untuk mengetahui kesalahan
import javax.imageio.ImageIO; // menghasilkan file dgn salah satu format gambar
import javax.swing.ImageIcon; //menghasilkan file
import javax.swing.JFileChooser; // membuat file 

/**
 *
 * @author nadyaocta
 */
public class KTP extends javax.swing.JFrame {

    /**
     * Creates new form percobaan3
     */
    public KTP() {
        initComponents(); // untuk menyambung ke class output
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jtengah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jatas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbawah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jkiri = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jatas1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbutton = new javax.swing.JPanel();
        jbuttondalam = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        register = new javax.swing.JButton();
        about = new javax.swing.JButton();
        jtengah1 = new javax.swing.JPanel();
        jhome = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jregister = new javax.swing.JPanel();
        pFoto = new javax.swing.JPanel();
        lFoto = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        teksnama = new javax.swing.JTextField();
        tekstempat = new javax.swing.JTextField();
        tekstanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        teksalamat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        teksrt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        teksrw = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tekskel = new javax.swing.JTextField();
        tekskec = new javax.swing.JTextField();
        tekskota = new javax.swing.JTextField();
        boxagama = new javax.swing.JComboBox<String>();
        boxstatus = new javax.swing.JComboBox<String>();
        boxgoldar = new javax.swing.JComboBox<String>();
        tekspekerjaan = new javax.swing.JTextField();
        rbWNA = new javax.swing.JRadioButton();
        rbWNI = new javax.swing.JRadioButton();
        cus = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jabout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbawah1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        data = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Konten");

        javax.swing.GroupLayout jtengahLayout = new javax.swing.GroupLayout(jtengah);
        jtengah.setLayout(jtengahLayout);
        jtengahLayout.setHorizontalGroup(
            jtengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtengahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jtengahLayout.setVerticalGroup(
            jtengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtengahLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jtengah, java.awt.BorderLayout.CENTER);

        jatas.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("SISTEM INFORMASI AKADEMIK");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("PROGRAM STUDI TEKNIK INFORMATIKA");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("UP. FTIK UNMUL");

        javax.swing.GroupLayout jatasLayout = new javax.swing.GroupLayout(jatas);
        jatas.setLayout(jatasLayout);
        jatasLayout.setHorizontalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatasLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jatasLayout.setVerticalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jatas, java.awt.BorderLayout.PAGE_START);

        jbawah.setBackground(new java.awt.Color(102, 0, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("MODUL PRATIKUM PEMROGRAMAN VISUAL JAVA");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Copyright@2015");

        javax.swing.GroupLayout jbawahLayout = new javax.swing.GroupLayout(jbawah);
        jbawah.setLayout(jbawahLayout);
        jbawahLayout.setHorizontalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbawahLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbawahLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(301, 301, 301))))
        );
        jbawahLayout.setVerticalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jbawah, java.awt.BorderLayout.PAGE_END);

        jkiri.setBackground(new java.awt.Color(102, 0, 0));

        jButton1.setText("Home");

        jButton2.setText("Profil");

        jButton3.setText("Galeri");

        jButton4.setText("Informasi");

        jButton5.setText("About");

        jButton6.setText("Keluar");

        javax.swing.GroupLayout jkiriLayout = new javax.swing.GroupLayout(jkiri);
        jkiri.setLayout(jkiriLayout);
        jkiriLayout.setHorizontalGroup(
            jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jkiriLayout.setVerticalGroup(
            jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkiriLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(60, 60, 60))
        );

        jFrame1.getContentPane().add(jkiri, java.awt.BorderLayout.LINE_START);

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jatas1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("SISTEM REGISTRASI KARTU TANDA PENDUDUK");

        jbutton.setBackground(new java.awt.Color(102, 0, 0));

        jbuttondalam.setBackground(new java.awt.Color(102, 0, 0));
        jbuttondalam.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jbuttonLayout = new javax.swing.GroupLayout(jbutton);
        jbutton.setLayout(jbuttonLayout);
        jbuttonLayout.setHorizontalGroup(
            jbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbuttonLayout.createSequentialGroup()
                .addComponent(jbuttondalam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jbuttonLayout.setVerticalGroup(
            jbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbuttonLayout.createSequentialGroup()
                .addComponent(jbuttondalam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kecil-766344782-ktp.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jPanel1.add(about);

        javax.swing.GroupLayout jatas1Layout = new javax.swing.GroupLayout(jatas1);
        jatas1.setLayout(jatas1Layout);
        jatas1Layout.setHorizontalGroup(
            jatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatas1Layout.createSequentialGroup()
                .addGroup(jatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jatas1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jatas1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jatas1Layout.setVerticalGroup(
            jatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatas1Layout.createSequentialGroup()
                .addGroup(jatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jatas1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jatas1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jatas1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jatas1, java.awt.BorderLayout.PAGE_START);

        jtengah1.setBackground(new java.awt.Color(153, 255, 153));
        jtengah1.setLayout(new java.awt.CardLayout());

        jhome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        jLabel23.setText("Penduduk hanya diperbolehkan memiliki 1 (satu) KTP yang tercantum Nomor Induk Kependudukan (NIK). ");

        jLabel31.setText("NIK merupakan identitas tunggal setiap penduduk dan berlaku seumur hidup.");

        jLabel32.setText("Nomor NIK yang ada di e-KTP nantinya akan dijadikan dasar dalam penerbitan Paspor, Surat Izin Mengemudi (SIM),");

        jLabel33.setText("Nomor Pokok Wajib Pajak (NPWP), Polis Asuransi, Sertifikat atas Hak Tanah dan penerbitan dokumen identitas lainnya ");

        jLabel34.setText("(Pasal 13 UU No. 23 Tahun 2006 tentang Adminduk)  ");

        javax.swing.GroupLayout jhomeLayout = new javax.swing.GroupLayout(jhome);
        jhome.setLayout(jhomeLayout);
        jhomeLayout.setHorizontalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel23))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jhomeLayout.setVerticalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(4, 4, 4)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jtengah1.add(jhome, "card2");

        jregister.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM ISIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 11))); // NOI18N

        pFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), new java.awt.Color(0, 0, 0)), "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 11))); // NOI18N

        javax.swing.GroupLayout pFotoLayout = new javax.swing.GroupLayout(pFoto);
        pFoto.setLayout(pFotoLayout);
        pFotoLayout.setHorizontalGroup(
            pFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        pFotoLayout.setVerticalGroup(
            pFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel24.setText("Nama");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel25.setText("Tempat/Tanggal Lahir");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel26.setText("Jenis Kelamin");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel27.setText("Alamat");

        teksnama.setBackground(new java.awt.Color(240, 240, 240));

        tekstempat.setBackground(new java.awt.Color(240, 240, 240));

        tekstanggal.setBackground(new java.awt.Color(240, 240, 240));

        jLabel7.setText("/");

        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        rbLaki.setText("Laki-Laki");

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        rbPerempuan.setText("Perempuan");

        teksalamat.setBackground(new java.awt.Color(240, 240, 240));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel28.setText("Kel/Desa");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel10.setText("Kecamatan");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel11.setText("Kota");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel29.setText("Agama");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel13.setText("Status");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel14.setText("Golongan Darah");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel15.setText("Pekerjaan");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel16.setText("Kewarganegaraan");

        teksrt.setBackground(new java.awt.Color(240, 240, 240));

        jLabel17.setText("/");

        teksrw.setBackground(new java.awt.Color(240, 240, 240));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel18.setText("RT/RW");

        tekskel.setBackground(new java.awt.Color(240, 240, 240));

        tekskec.setBackground(new java.awt.Color(240, 240, 240));

        tekskota.setBackground(new java.awt.Color(240, 240, 240));

        boxagama.setBackground(new java.awt.Color(240, 240, 240));
        boxagama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISLAM", "KATHOLIK", "PROTESTAN", "HINDU", "BUDHA", "LAINNYA" }));
        boxagama.setToolTipText("");

        boxstatus.setBackground(new java.awt.Color(240, 240, 240));
        boxstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KAWIN", "BELUM KAWIN" }));

        boxgoldar.setBackground(new java.awt.Color(240, 240, 240));
        boxgoldar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));

        tekspekerjaan.setBackground(new java.awt.Color(240, 240, 240));

        buttonGroup2.add(rbWNA);
        rbWNA.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        rbWNA.setText("WNA");

        buttonGroup2.add(rbWNI);
        rbWNI.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        rbWNI.setText("WNI");

        cus.setText("Choose");
        cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusActionPerformed(evt);
            }
        });

        jButton7.setText("Register");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel35.setText("Pilih fotomu 3x4");

        javax.swing.GroupLayout jregisterLayout = new javax.swing.GroupLayout(jregister);
        jregister.setLayout(jregisterLayout);
        jregisterLayout.setHorizontalGroup(
            jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jregisterLayout.createSequentialGroup()
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel26))
                            .addGroup(jregisterLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel11))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jregisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teksnama, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekspekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekskel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekskec, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekskota, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teksalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tekstempat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jregisterLayout.createSequentialGroup()
                                .addComponent(rbLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPerempuan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tekstanggal))
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addComponent(teksrt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teksrw, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addComponent(rbWNA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbWNI)))
                .addGap(55, 55, 55)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(jLabel35))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jregisterLayout.setVerticalGroup(
            jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jregisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(teksnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tekstempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tekstanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jregisterLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel27))
                            .addGroup(jregisterLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(teksalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(teksrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(teksrw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(tekskel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tekskec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tekskota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(boxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(boxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jregisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(boxgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tekspekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbWNA)
                        .addComponent(rbWNI)
                        .addComponent(jButton7)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtengah1.add(jregister, "card3");

        jabout.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Nadya Octavia Islami");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel20.setText("1515015147");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel21.setText("C2.2015");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/64376.jpg"))); // NOI18N

        javax.swing.GroupLayout jaboutLayout = new javax.swing.GroupLayout(jabout);
        jabout.setLayout(jaboutLayout);
        jaboutLayout.setHorizontalGroup(
            jaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaboutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel5))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jaboutLayout.setVerticalGroup(
            jaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaboutLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jaboutLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel20)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jtengah1.add(jabout, "card4");

        getContentPane().add(jtengah1, java.awt.BorderLayout.CENTER);

        jbawah1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Copyright@C2.2015");

        javax.swing.GroupLayout jbawah1Layout = new javax.swing.GroupLayout(jbawah1);
        jbawah1.setLayout(jbawah1Layout);
        jbawah1Layout.setHorizontalGroup(
            jbawah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbawah1Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jbawah1Layout.setVerticalGroup(
            jbawah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawah1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jbawah1, java.awt.BorderLayout.PAGE_END);

        data.setText("Data");

        jMenuItem2.setText("Input Data");
        data.add(jMenuItem2);

        jMenuItem3.setText("Cari Data");
        data.add(jMenuItem3);

        jMenuItem4.setText("Data Yudisium");
        data.add(jMenuItem4);

        jMenuBar1.add(data);

        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        jhome.setVisible(true); // panel tertampil
        jregister.setVisible(false); // panel tidak tertampil
        jabout.setVisible(false); // panel tidak tertampil
    }//GEN-LAST:event_homeActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        jregister.setVisible(true); // panel tertampil
        jhome.setVisible(false); // panel tidak tertampil
        jabout.setVisible(false); // panel tidak tertampil
    }//GEN-LAST:event_registerActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_keluarActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
         System.exit(0); // kelua dari running frame
    }//GEN-LAST:event_keluarMouseClicked

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        jabout.setVisible(true); // panel tertampil
        jhome.setVisible(false); // panel tidak tertampil
        jregister.setVisible(false); // panel tidak tertampil
    }//GEN-LAST:event_aboutActionPerformed

    private void cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusActionPerformed
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);
        
        File filegambar = null;
        if (returnVal == JFileChooser.APPROVE_OPTION){
            filegambar = OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try{
            BufferedImage gambar=ImageIO.read(filegambar);
            ImageIcon icon = new ImageIcon(gambar.getScaledInstance(150, 200, 0));            
            
            lFoto.setIcon(icon);
            
            
//            lFoto1.setIcon(icon);
//            lFoto1.setVisible(true);
        }
        catch(IOException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_cusActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        teksnama.setText("");
        tekstempat.setText("");
        tekstanggal.setText("");
        teksalamat.setText("");
        teksrt.setText("");
        teksrw.setText("");
        tekskel.setText("");
        tekskec.setText("");
        tekskota.setText("");
        tekspekerjaan.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        boxagama.setSelectedItem(false);
        boxgoldar.setSelectedItem(false);
        boxstatus.setSelectedItem(false);
        // mereset atau menormalkan kembali layar yang telah terisi secara otomatis
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                output tampil = new output(); // untuk menghubung ke frame output
        output.namaout.setText(this.teksnama.getText()); // mengambil isi dari nama lalu terhubung ke frame output 
        output.tempatout.setText(this.tekstempat.getText());  // mengambil isi dari tempat lalu terhubung ke frame output 
        
        output.tanggalout.setText(this.tekstanggal.getText());  // mengambil isi dari tanggal lalu terhubung ke frame output 
        output.alamatout.setText(this.teksalamat.getText());  // mengambil isi dari alamat lalu terhubung ke frame output 
        output.rtout.setText(this.teksrt.getText());  // mengambil isi dari rt lalu terhubung ke frame output 
        output.tfRW1.setText(this.teksrw.getText());  // mengambil isi dari rw lalu terhubung ke frame output 
        output.kelout.setText(this.tekskel.getText());  // mengambil isi dari kelurahan lalu terhubung ke frame output 
        output.kecout.setText(this.tekskec.getText());  // mengambil isi dari kecamatan lalu terhubung ke frame output 
        output.kotaout.setText(this.tekskota.getText());  // mengambil isi dari kota lalu terhubung ke frame output 
        output.agamaout.setText(this.boxagama.getSelectedItem().toString());  // mengambil isi dari agama lalu terhubung ke frame output 
        output.statusout.setText(this.boxstatus.getSelectedItem().toString());  // mengambil isi dari status lalu terhubung ke frame output 
        output.goldarout.setText(this.boxgoldar.getSelectedItem().toString());  // mengambil isi dari goldar lalu terhubung ke frame output 
        output.pekerjaanout.setText(this.tekspekerjaan.getText());  // mengambil isi dari pekerjaan lalu terhubung ke frame output 
        
        if(rbLaki.isSelected()){
            output.tfJK1.setText(rbLaki.getText());
        }
        else if(rbPerempuan.isSelected()){
            output.tfJK1.setText(rbPerempuan.getText());
        }
        if(rbWNA.isSelected()){
            output.wargaout.setText(rbWNA.getText());
        }
        
        else if(rbWNI.isSelected()){
            output.wargaout.setText(rbWNI.getText());
        }
        
        output.lFoto1.setIcon(this.lFoto.getIcon());
        tampil.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KTP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JComboBox<String> boxagama;
    private javax.swing.JComboBox<String> boxgoldar;
    private javax.swing.JComboBox<String> boxstatus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cus;
    private javax.swing.JMenu data;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jabout;
    private javax.swing.JPanel jatas;
    private javax.swing.JPanel jatas1;
    private javax.swing.JPanel jbawah;
    private javax.swing.JPanel jbawah1;
    private javax.swing.JPanel jbutton;
    private javax.swing.JPanel jbuttondalam;
    private javax.swing.JPanel jhome;
    private javax.swing.JPanel jkiri;
    private javax.swing.JPanel jregister;
    private javax.swing.JPanel jtengah;
    private javax.swing.JPanel jtengah1;
    private javax.swing.JMenu keluar;
    private javax.swing.JLabel lFoto;
    private javax.swing.JPanel pFoto;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JRadioButton rbWNA;
    private javax.swing.JRadioButton rbWNI;
    private javax.swing.JButton register;
    private javax.swing.JTextField teksalamat;
    private javax.swing.JTextField tekskec;
    private javax.swing.JTextField tekskel;
    private javax.swing.JTextField tekskota;
    private javax.swing.JTextField teksnama;
    private javax.swing.JTextField tekspekerjaan;
    private javax.swing.JTextField teksrt;
    private javax.swing.JTextField teksrw;
    private javax.swing.JTextField tekstanggal;
    private javax.swing.JTextField tekstempat;
    // End of variables declaration//GEN-END:variables
}
